/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lVuQcYSRpgb
 */
import { Button } from "@/components/ui/button"

export function TestUI() {
  return (
    <div className="bg-[#bd1e59] min-h-screen flex flex-col items-center justify-center">
      <div className="flex justify-between items-center w-full max-w-4xl px-8">
        <div className="text-white text-center">
          <h1 className="text-4xl font-bold mb-4">PLAYER 1</h1>
          <div className="text-9xl font-semibold">0</div>
          <div className="bg-[#db7093] text-white text-center py-4 px-8 mt-4 rounded-lg">
            <h2 className="text-xl font-bold">CURRENT</h2>
            <p className="text-5xl font-semibold">0</p>
          </div>
        </div>
        <div className="flex flex-col items-center">
          <Button className="bg-white text-[#bd1e59] font-bold py-2 px-4 rounded-full mb-4 flex items-center space-x-2">
            <RefreshCwIcon className="text-[#bd1e59]" />
            <span>NEW GAME</span>
          </Button>
          <div className="flex space-x-4">
            <Button className="bg-white text-[#bd1e59] font-bold py-2 px-4 rounded-full flex items-center space-x-2">
              <Dice1Icon className="text-[#bd1e59]" />
              <span>ROLL DICE</span>
            </Button>
            <Button className="bg-white text-[#bd1e59] font-bold py-2 px-4 rounded-full flex items-center space-x-2">
              <HandIcon className="text-[#bd1e59]" />
              <span>HOLD</span>
            </Button>
          </div>
        </div>
        <div className="text-white text-center">
          <h1 className="text-4xl font-bold mb-4">PLAYER 2</h1>
          <div className="text-9xl font-semibold">0</div>
          <div className="bg-[#db7093] text-white text-center py-4 px-8 mt-4 rounded-lg">
            <h2 className="text-xl font-bold">CURRENT</h2>
            <p className="text-5xl font-semibold">0</p>
          </div>
        </div>
      </div>
    </div>
  )
}


function RefreshCwIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" />
      <path d="M21 3v5h-5" />
      <path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" />
      <path d="M8 16H3v5" />
    </svg>
  )
}


function Dice1Icon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" ry="2" />
      <path d="M12 12h.01" />
    </svg>
  )
}


function HandIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 11V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v0" />
      <path d="M14 10V4a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v2" />
      <path d="M10 10.5V6a2 2 0 0 0-2-2v0a2 2 0 0 0-2 2v8" />
      <path d="M18 8a2 2 0 1 1 4 0v6a8 8 0 0 1-8 8h-2c-2.8 0-4.5-.86-5.99-2.34l-3.6-3.6a2 2 0 0 1 2.83-2.82L7 15" />
    </svg>
  )
}
